---
steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - gcr.io/snp-linux/containers/analysis:0.1
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/snp-linux/containers/analysis:0.1